### ISSUE TITLE
Repository Structure

### ISSUE THREAD

**Issue by PhoneDroid** [temper-studios/graph-file-format#4]
<br>

Some general things I would love for you to consider:

<br>

- **Add a license**
 
  I would recommend **AGPLv3**

  Check out https://choosealicense.com/licenses/

  <br>

- Disable things you don't use

   - Packages
   - Projects
   - Actions
   - Releases ( as long as you don't have one )

<br>

- Add a description & tags
  
  ```
  Text data format designed for games.
  ```
  
  - `file-format`
  - `human-readable`
  - `game-data`
  - `text-based`
  - `hierarchical`
  - `reference-implementation`

<br>

**Comment by temper-studios** [comment]
I'll add a licence (probably MIT). I like how simple it is right now. Plain text readme without buttons is the way to go

**Comment by temper-studios** [comment]
I'll get round to tidying up later
